### PR TITLE
module1: Updated README.md, added ble_mesh folders, and added .gitignore

### PR DESCRIPTION
**Pull request by josh-minch**
- Updated README.md with instructions on how to build and flash an application to the Carbon.
- Added ble_mesh_cli and ble_mesh_srv folders with code and configuration files for setting up a Bluetooth mesh network.
- Removed build folders found in ble_mesh_cli and ble_mesh_srv and added them to .gitignore.

### CODE REVIEW

**Review by teearex — APPROVED** [review]
+1 PR

**Comment by sdrobertw** [comment]
Wow! @josh-minch Very nicely done! Thank you! 

I will sign off as second reviewer. Keep it up!

@teearex feel free to merge this PR.

**Comment by sdrobertw** [comment]
Wow! @josh-minch Very nicely done! Thank you!

I will sign off as second reviewer. Keep it up!

@teearex feel free to merge this PR.

**Review by fixxxxxxer — APPROVED** [review]
Wow! @josh-minch Very nicely done! Thank you!

I will sign off as second reviewer. Keep it up!

@teearex feel free to merge this PR.

**Comment by fixxxxxxer** [comment]
@teearex you can do the honors of merging the PR 👍 💃 🎃

**Comment by fixxxxxxer** [comment]
@teearex new on this PR? Please merge. Are you waiting for more input?

**Comment by fixxxxxxer** [comment]
First big merge! Congrats! :)

**Pull request merged**
