### PR TITLE
home_node: wrote instructions to install a web server

### PR DESCRIPTION
**Pull request by teearex**
Signed-off-by: RunXuan Tay <rxtay@ucsd.edu>

### CODE REVIEW

**Comment by fixxxxxxer** [comment]
@teearex please sign all commits and PR:

Signed-ff-by: Firstname Lastname <email@domain.com>

Contribution / Signing conventions are important and should be enforced throughout the life of your repo.

**Comment by fixxxxxxer** [comment]
@teearex  Pull request description should be detailed and should provide a summary of each commit.

**Comment by Mani-Sadhasivam** [comment]
@shadowend56 You _should_ not merge PR's without review from 96Boards team. We expect the community to contribute to our Projects Org and at the same time we have the responsibility to make all the contents to be of same standard. Once any one of the our team member approves the PR then only we will merge.

Thanks.

**Comment by fixxxxxxer** [comment]
@teearex @shadowend56 and others, I think what is most important to note here:

- A review process needs to be put in place for your team. There should be 1-2 maintainers and a chain of review.
- Each commit and each PR must follow conventions. For example, they must be signed and must be accepted only when all conventions have been followed.
   - This is not only intended to build a strong repo, but also to set an example and to provide your own personal handles with the most mature looking contributions. You will want your git history to shine and not looks lazy. We will surely talk about this tomorrow in our 1:1 meeting.
- 96Boards team will not review all/most of your PR, unless requested. We expect your team to manage your own repo, end-to-end. But in order to do this, I want to make sure you are making the right moves each time a change is made.

**Pull request merged**
